
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shadab
 */
public class loginform extends javax.swing.JFrame {

    /**
     * Creates new form loginform
     */
    public loginform() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header_panel = new javax.swing.JPanel();
        login_title = new javax.swing.JLabel();
        close_panel = new javax.swing.JLabel();
        minimize_label = new javax.swing.JLabel();
        login_panel = new javax.swing.JPanel();
        username_label = new javax.swing.JLabel();
        jSeparator1_usename = new javax.swing.JSeparator();
        jLabel1_pass = new javax.swing.JLabel();
        jSeparator1_pass = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1_usename = new javax.swing.JTextField();
        jButton1_signIN = new javax.swing.JButton();
        jButton1_cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1_pass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header_panel.setBackground(new java.awt.Color(41, 241, 195));

        login_title.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        login_title.setForeground(new java.awt.Color(255, 255, 255));
        login_title.setText("log IN");

        close_panel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close_panel.setForeground(new java.awt.Color(255, 255, 255));
        close_panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Multiply_32px.png"))); // NOI18N
        close_panel.setText("    ");
        close_panel.setToolTipText("");
        close_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_panelMouseClicked(evt);
            }
        });

        minimize_label.setForeground(new java.awt.Color(255, 255, 255));
        minimize_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Subtract_32px_1.png"))); // NOI18N
        minimize_label.setText(" ");
        minimize_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout header_panelLayout = new javax.swing.GroupLayout(header_panel);
        header_panel.setLayout(header_panelLayout);
        header_panelLayout.setHorizontalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login_title, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimize_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(close_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        header_panelLayout.setVerticalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(close_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimize_label))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(header_panelLayout.createSequentialGroup()
                .addComponent(login_title, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(header_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, -1));

        login_panel.setBackground(new java.awt.Color(46, 49, 49));
        login_panel.setMinimumSize(new java.awt.Dimension(436, 340));
        login_panel.setPreferredSize(new java.awt.Dimension(436, 340));

        username_label.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        username_label.setForeground(new java.awt.Color(255, 255, 255));
        username_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Customer_32px.png"))); // NOI18N
        username_label.setText("username");

        jLabel1_pass.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel1_pass.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Password_32px.png"))); // NOI18N
        jLabel1_pass.setText("password");

        jPasswordField1.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(null);
        jPasswordField1.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);

        jTextField1_usename.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1_usename.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField1_usename.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1_usename.setText(" ");
        jTextField1_usename.setBorder(null);

        jButton1_signIN.setBackground(new java.awt.Color(0, 255, 0));
        jButton1_signIN.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jButton1_signIN.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_signIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Swimming_32px.png"))); // NOI18N
        jButton1_signIN.setText("sign IN");
        jButton1_signIN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_signIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_signINActionPerformed(evt);
            }
        });

        jButton1_cancel.setBackground(new java.awt.Color(207, 0, 15));
        jButton1_cancel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jButton1_cancel.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Banned_32px.png"))); // NOI18N
        jButton1_cancel.setText("Cancel");
        jButton1_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_cancelMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Registration_32px.png"))); // NOI18N
        jLabel1.setText("Create a new account");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jCheckBox1_pass.setBackground(new java.awt.Color(102, 102, 102));
        jCheckBox1_pass.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jCheckBox1_pass.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1_pass.setText("show pass");
        jCheckBox1_pass.setBorder(null);
        jCheckBox1_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1_passActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout login_panelLayout = new javax.swing.GroupLayout(login_panel);
        login_panel.setLayout(login_panelLayout);
        login_panelLayout.setHorizontalGroup(
            login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_panelLayout.createSequentialGroup()
                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(login_panelLayout.createSequentialGroup()
                        .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(login_panelLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(login_panelLayout.createSequentialGroup()
                                        .addComponent(username_label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField1_usename, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(login_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel1_pass)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(login_panelLayout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jButton1_cancel)
                                        .addGap(67, 67, 67)
                                        .addComponent(jButton1_signIN))))
                            .addGroup(login_panelLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator1_usename, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(jSeparator1_pass)))
                            .addGroup(login_panelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jCheckBox1_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        login_panelLayout.setVerticalGroup(
            login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_panelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(username_label)
                    .addComponent(jTextField1_usename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1_usename, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(login_panelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1_pass))
                    .addGroup(login_panelLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1_pass)
                .addGap(1, 1, 1)
                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_signIN)
                    .addComponent(jButton1_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(login_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 430, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_panelMouseClicked
       
       System.exit(0); 
        
    }//GEN-LAST:event_close_panelMouseClicked

    private void minimize_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_labelMouseClicked
      
        
this.setState(JFrame.ICONIFIED);
        

// TODO add your handling code here:
    }//GEN-LAST:event_minimize_labelMouseClicked

    private void jButton1_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_cancelMouseClicked
       
        
System.exit(0);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1_cancelMouseClicked

    private void jCheckBox1_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1_passActionPerformed
       
      if(jCheckBox1_pass.isSelected())  
      {   
      jPasswordField1 .setEchoChar((char)0);
      }
      else
      {
         jPasswordField1 .setEchoChar('*') ;  
      }




// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1_passActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       
      signUP_form sf= new signUP_form();
        
      sf.setVisible(true);
        sf.pack();
        sf.setLocationRelativeTo(null);
        sf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();


// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1_signINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_signINActionPerformed
         
          try {
            PreparedStatement ps;
            ResultSet rs;
            String username=jTextField1_usename.getText();
            String pass= String.valueOf(jPasswordField1.getPassword() );
            
            String query="SELECT uname,pass,pic,id from`user` WHERE uname=? and pass=?";
            
            
            
            
            
            
            ps=myconnection.getconnection().prepareStatement(query);
            
            
            
            ps.setString(1, username);
            
            ps.setString(2, pass);
            
            rs=ps.executeQuery();
            
            if(rs.next())
            {
                 //get the current user id
                mycontactform.currentUserId=rs.getInt("id");
               System.out.println(rs.getInt("id")+"from Login");
                
                mycontactform rf= new mycontactform();
        
      rf.setVisible(true);
        rf.pack();
        rf.setLocationRelativeTo(null);
        rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
           
  //show the user profile pic on top
          rf.jLabel1_minipic.setIcon(new myfunc().ResizePic(null,rs.getBytes(3),rf.jLabel1_minipic.getWidth(),rf.jLabel1_minipic.getHeight()));  
            
          rf.jLabel1_usename.setText(rs.getString(1));
           this.dispose();
          
          
            }       

                
            else
            {
                
                JOptionPane.showMessageDialog(null,"wrong username or password entered");
            }       
        }
        
        catch (SQLException ex) {
            Logger.getLogger(loginform.class.getName()).log(Level.SEVERE, null, ex); 
        
        
        
        
        
        }
        
        
    }//GEN-LAST:event_jButton1_signINActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close_panel;
    private javax.swing.JPanel header_panel;
    private javax.swing.JButton jButton1_cancel;
    private javax.swing.JButton jButton1_signIN;
    private javax.swing.JCheckBox jCheckBox1_pass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_pass;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1_pass;
    private javax.swing.JSeparator jSeparator1_usename;
    private javax.swing.JTextField jTextField1_usename;
    private javax.swing.JPanel login_panel;
    private javax.swing.JLabel login_title;
    private javax.swing.JLabel minimize_label;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
