
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shadab
 */
public class mycontactform extends javax.swing.JFrame {

    /**
     * Creates new form mycontactform
     */
    
    String imgpath=null;
    
    int pos=0;
    
    public static int currentUserId;
    
    
    
    
    public mycontactform() {
        initComponents();
       
        this.setLocationRelativeTo(null);
       populatedJtable();
        jTable1_info.setShowGrid(true);
        JTableHeader th= jTable1_info.getTableHeader();
        
        th.setForeground(Color.blue);
        th.setFont(new Font ("Tahoma",Font.PLAIN,14));
        
         System.out.println(currentUserId+ "from contact"); 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1_gray = new javax.swing.JPanel();
        mycontact_panel = new javax.swing.JPanel();
        jLabel1_mycontact = new javax.swing.JLabel();
        jLabel1_yello = new javax.swing.JLabel();
        jLabel1_usename = new javax.swing.JLabel();
        jLabel1_minipic = new javax.swing.JLabel();
        jLabel1_close = new javax.swing.JLabel();
        jLabel1_mini = new javax.swing.JLabel();
        jLabel1_fname = new javax.swing.JLabel();
        jSeparator1_fname = new javax.swing.JSeparator();
        jLabel1_lname = new javax.swing.JLabel();
        jSeparator1_fname1 = new javax.swing.JSeparator();
        jLabel1_phone = new javax.swing.JLabel();
        jSeparator1_phone = new javax.swing.JSeparator();
        jLabel1_email = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField1_fname = new javax.swing.JTextField();
        jTextField1_lname = new javax.swing.JTextField();
        jTextField1_phone = new javax.swing.JTextField();
        jTextField1_email = new javax.swing.JTextField();
        jLabel1_image = new javax.swing.JLabel();
        jLabel1_picframe = new javax.swing.JLabel();
        jLabel1_address = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1_adress = new javax.swing.JTextArea();
        jLabel1_ID = new javax.swing.JLabel();
        jComboBox1_email = new javax.swing.JComboBox();
        jButton1_picsel = new javax.swing.JButton();
        jButton1_edit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1_info = new javax.swing.JTable();
        jButton1_add1 = new javax.swing.JButton();
        jLabel1_combo1 = new javax.swing.JLabel();
        jTextField1_id = new javax.swing.JTextField();
        jButton1_del = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1next = new javax.swing.JButton();
        jButton1_rt = new javax.swing.JButton();
        jButton1_lf = new javax.swing.JButton();
        jButton1_lfnext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1_gray.setBackground(new java.awt.Color(25, 181, 254));
        jPanel1_gray.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1_gray.setToolTipText("");

        mycontact_panel.setBackground(new java.awt.Color(34, 167, 240));
        mycontact_panel.setForeground(new java.awt.Color(102, 102, 102));

        jLabel1_mycontact.setBackground(new java.awt.Color(34, 167, 240));
        jLabel1_mycontact.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel1_mycontact.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_mycontact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Address_Book_32px.png"))); // NOI18N
        jLabel1_mycontact.setText("MyContacts");

        jLabel1_yello.setBackground(new java.awt.Color(240, 255, 0));
        jLabel1_yello.setText(" ");

        jLabel1_usename.setBackground(new java.awt.Color(34, 167, 240));
        jLabel1_usename.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1_usename.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_usename.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Customer_32px.png"))); // NOI18N
        jLabel1_usename.setText("UserName");

        jLabel1_minipic.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1_minipic.setText(" ");
        jLabel1_minipic.setOpaque(true);

        javax.swing.GroupLayout mycontact_panelLayout = new javax.swing.GroupLayout(mycontact_panel);
        mycontact_panel.setLayout(mycontact_panelLayout);
        mycontact_panelLayout.setHorizontalGroup(
            mycontact_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mycontact_panelLayout.createSequentialGroup()
                .addGroup(mycontact_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1_yello, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mycontact_panelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1_usename, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jLabel1_minipic, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231)
                .addComponent(jLabel1_mycontact, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mycontact_panelLayout.setVerticalGroup(
            mycontact_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mycontact_panelLayout.createSequentialGroup()
                .addComponent(jLabel1_yello)
                .addGap(1, 1, 1)
                .addComponent(jLabel1_usename, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1_minipic, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(mycontact_panelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1_mycontact))
        );

        jLabel1_close.setForeground(new java.awt.Color(207, 0, 15));
        jLabel1_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Shutdown_24px_2.png"))); // NOI18N
        jLabel1_close.setText(" ");
        jLabel1_close.setToolTipText("");
        jLabel1_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_closeMouseClicked(evt);
            }
        });

        jLabel1_mini.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1_mini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Minus_24px.png"))); // NOI18N
        jLabel1_mini.setText(" ");
        jLabel1_mini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1_mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_miniMouseClicked(evt);
            }
        });

        jLabel1_fname.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1_fname.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_fname.setText("FirstName");

        jSeparator1_fname.setForeground(new java.awt.Color(51, 255, 0));
        jSeparator1_fname.setOpaque(true);

        jLabel1_lname.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1_lname.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_lname.setText("LastName");

        jSeparator1_fname1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1_fname1.setOpaque(true);

        jLabel1_phone.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1_phone.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_phone.setText("Phone");

        jSeparator1_phone.setBackground(new java.awt.Color(0, 255, 0));
        jSeparator1_phone.setOpaque(true);

        jLabel1_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1_email.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_email.setText("Email");

        jSeparator1.setBackground(new java.awt.Color(0, 204, 0));
        jSeparator1.setOpaque(true);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setOpaque(true);

        jTextField1_fname.setBackground(new java.awt.Color(25, 181, 254));
        jTextField1_fname.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField1_fname.setText(" ");
        jTextField1_fname.setBorder(null);
        jTextField1_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_fnameActionPerformed(evt);
            }
        });

        jTextField1_lname.setBackground(new java.awt.Color(25, 181, 254));
        jTextField1_lname.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jTextField1_lname.setText(" ");
        jTextField1_lname.setBorder(null);

        jTextField1_phone.setBackground(new java.awt.Color(25, 181, 254));
        jTextField1_phone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField1_phone.setText(" ");
        jTextField1_phone.setBorder(null);
        jTextField1_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_phoneActionPerformed(evt);
            }
        });

        jTextField1_email.setBackground(new java.awt.Color(25, 181, 254));
        jTextField1_email.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jTextField1_email.setText(" ");
        jTextField1_email.setBorder(null);

        jLabel1_image.setBackground(new java.awt.Color(238, 238, 238));
        jLabel1_image.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1_image.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Full_Image_32px.png"))); // NOI18N
        jLabel1_image.setText("ProfilePic:");

        jLabel1_picframe.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1_picframe.setText(" ");
        jLabel1_picframe.setOpaque(true);

        jLabel1_address.setBackground(new java.awt.Color(238, 238, 238));
        jLabel1_address.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1_address.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_address.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_address.setText("Address:");

        jTextArea1_adress.setColumns(20);
        jTextArea1_adress.setRows(5);
        jScrollPane1.setViewportView(jTextArea1_adress);

        jLabel1_ID.setBackground(new java.awt.Color(238, 238, 238));
        jLabel1_ID.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1_ID.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_ID.setText("ID:");

        jComboBox1_email.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox1_email.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "family", "work", "friends" }));
        jComboBox1_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_emailActionPerformed(evt);
            }
        });

        jButton1_picsel.setBackground(new java.awt.Color(0, 181, 204));
        jButton1_picsel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton1_picsel.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_picsel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Full_Image_32px.png"))); // NOI18N
        jButton1_picsel.setText("Browse");
        jButton1_picsel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_picsel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_picselActionPerformed(evt);
            }
        });

        jButton1_edit.setBackground(new java.awt.Color(32, 185, 115));
        jButton1_edit.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jButton1_edit.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Edit_Property_32px.png"))); // NOI18N
        jButton1_edit.setText("Edit");
        jButton1_edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_editActionPerformed(evt);
            }
        });

        jTable1_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1_info.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1_info.setRowHeight(12);
        jTable1_info.setRowMargin(2);
        jTable1_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_infoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1_info);

        jButton1_add1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1_add1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jButton1_add1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_add1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Add_User_Male_32px_3.png"))); // NOI18N
        jButton1_add1.setText("add");
        jButton1_add1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_add1ActionPerformed(evt);
            }
        });

        jLabel1_combo1.setBackground(new java.awt.Color(238, 238, 238));
        jLabel1_combo1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1_combo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_combo1.setText("group");

        jTextField1_id.setBackground(new java.awt.Color(25, 181, 254));
        jTextField1_id.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jTextField1_id.setText(" ");
        jTextField1_id.setBorder(null);
        jTextField1_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_idActionPerformed(evt);
            }
        });

        jButton1_del.setBackground(new java.awt.Color(255, 0, 0));
        jButton1_del.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jButton1_del.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Banned_32px.png"))); // NOI18N
        jButton1_del.setText("Delete");
        jButton1_del.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_delActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("List of Contacts");

        jButton1next.setBackground(new java.awt.Color(44, 130, 201));
        jButton1next.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1next.setForeground(new java.awt.Color(255, 255, 255));
        jButton1next.setText("<<");
        jButton1next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1nextActionPerformed(evt);
            }
        });

        jButton1_rt.setBackground(new java.awt.Color(1, 50, 67));
        jButton1_rt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1_rt.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_rt.setText("<");
        jButton1_rt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_rt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_rtActionPerformed(evt);
            }
        });

        jButton1_lf.setBackground(new java.awt.Color(31, 58, 147));
        jButton1_lf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1_lf.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_lf.setText(">");
        jButton1_lf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_lf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_lfActionPerformed(evt);
            }
        });

        jButton1_lfnext.setBackground(new java.awt.Color(44, 130, 201));
        jButton1_lfnext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1_lfnext.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_lfnext.setText(" >>");
        jButton1_lfnext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_lfnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_lfnextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_grayLayout = new javax.swing.GroupLayout(jPanel1_gray);
        jPanel1_gray.setLayout(jPanel1_grayLayout);
        jPanel1_grayLayout.setHorizontalGroup(
            jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_grayLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(mycontact_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_grayLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1_mini)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1_close)
                .addContainerGap())
            .addGroup(jPanel1_grayLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1_grayLayout.createSequentialGroup()
                        .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1_grayLayout.createSequentialGroup()
                                .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_grayLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jSeparator1_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(86, 86, 86))
                                    .addGroup(jPanel1_grayLayout.createSequentialGroup()
                                        .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1_grayLayout.createSequentialGroup()
                                                .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1_lname)
                                                    .addComponent(jLabel1_phone)
                                                    .addComponent(jLabel1_fname))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField1_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField1_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jSeparator1_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField1_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jSeparator1_fname1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1_grayLayout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel1_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField1_id, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(81, 81, 81)))
                                .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1_grayLayout.createSequentialGroup()
                                        .addGap(121, 121, 121)
                                        .addComponent(jLabel1_image, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1_grayLayout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1_grayLayout.createSequentialGroup()
                                        .addComponent(jLabel1_address)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1_grayLayout.createSequentialGroup()
                                        .addComponent(jLabel1_picframe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(jButton1_picsel))))
                            .addGroup(jPanel1_grayLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1_grayLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton1next, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1_rt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1_lf, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1_lfnext, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1_grayLayout.createSequentialGroup()
                                        .addComponent(jLabel1_combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox1_email, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1_grayLayout.createSequentialGroup()
                        .addComponent(jLabel1_email)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(333, 333, 333)
                        .addComponent(jButton1_del)
                        .addGap(35, 35, 35)
                        .addComponent(jButton1_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jButton1_add1)
                        .addGap(23, 23, 23))))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1_grayLayout.setVerticalGroup(
            jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_grayLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_mini)
                    .addComponent(jLabel1_close, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(mycontact_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1_grayLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1_fname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1_grayLayout.createSequentialGroup()
                                .addComponent(jLabel1_lname)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel1_phone))
                            .addGroup(jPanel1_grayLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1_fname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jTextField1_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1_email)
                                    .addComponent(jTextField1_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1_grayLayout.createSequentialGroup()
                        .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1_grayLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel1_image, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_grayLayout.createSequentialGroup()
                                .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1_picsel)
                                    .addComponent(jLabel1_picframe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1_address))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_del)
                    .addComponent(jButton1_edit)
                    .addComponent(jButton1_add1)
                    .addComponent(jComboBox1_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1_combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1_grayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1next)
                    .addComponent(jLabel1)
                    .addComponent(jButton1_rt)
                    .addComponent(jButton1_lf)
                    .addComponent(jButton1_lfnext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_gray, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_gray, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void populatedJtable()
    {
        
      contactQuery cq= new contactQuery();
      
      ArrayList<contact> ctList=cq.contactList(currentUserId);
      
     String[] colNames={"    Id","FirstName","LastName","Group","Phone","Email","Adress","  Image"};
     
     Object[][] rows=new Object[ctList.size()][8];
     
     
     for(int i=0; i<ctList.size();i++)
         
     {
         
         rows[i][0]=ctList.get(i).getCid();
         
         rows[i][1]=ctList.get(i).getFname();
         
         rows[i][2]=ctList.get(i).getLname();
         
         rows[i][3]=ctList.get(i).getGroupc();
         
         rows[i][4]=ctList.get(i).getPhone();
         rows [i][5]=ctList.get(i).getEmail();
         rows [i][6]=ctList.get(i).getAddress();
         
         
          
          
         
        if(ctList.get(i).getPic()!=null)
         {
         
        
         
     rows[i][7]= new ImageIcon(new ImageIcon(ctList.get(i).getPic()).getImage().getScaledInstance(120,80,Image.SCALE_SMOOTH)); 
         
         
       
         
         
         
         
         
       // rows[i][7]=pic; //.getScaledInstance(70,100,Image.SCALE_SMOOTH));
         
     }
     else
        {
             
            rows[i][7]=null; 
         }
    
        mymodel mmd=new mymodel(rows,colNames);
        
        jTable1_info.setModel(mmd);
          
         jTable1_info.setRowHeight(80);
         jTable1_info.getColumnModel().getColumn(7).setPreferredWidth(120);
           
        
         
    }
    
    
    }
    
      

    
    
    
    
    private void jLabel1_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_closeMouseClicked

        System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1_closeMouseClicked

    private void jLabel1_miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_miniMouseClicked

        this.setState(JFrame.ICONIFIED);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1_miniMouseClicked

    private void jTextField1_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_fnameActionPerformed

    private void jComboBox1_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1_emailActionPerformed

    private void jButton1_picselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_picselActionPerformed

        
             
   myfunc mf=new myfunc();
   
  imgpath= mf.BrowseImage(jLabel1_picframe);

System.out.println(imgpath);
        
        
        
        
        
    }//GEN-LAST:event_jButton1_picselActionPerformed

    public void clearFields()
    {
        
             jTextField1_id.setText("");
             jTextField1_fname.setText("");
             jTextField1_lname.setText("");
                jTextField1_phone.setText("");
                   jTextField1_email.setText("");
                      jTextArea1_adress.setText("");
        jComboBox1_email.setSelectedIndex(0);
        
        jLabel1_picframe.setIcon(null);
        imgpath=null;
        
    }
    
   private void showData( int Index)
   {
       
       

jTextField1_fname.setText(jTable1_info.getValueAt(Index, 1).toString());


jTextField1_lname.setText(jTable1_info.getValueAt(Index, 2).toString());

jComboBox1_email.setSelectedItem(jTable1_info.getValueAt(Index, 3));
jTextField1_phone.setText(jTable1_info.getValueAt(Index, 4).toString());
jTextField1_email.setText(jTable1_info.getValueAt(Index, 5).toString());
jTextArea1_adress.setText(jTable1_info.getValueAt(Index, 6).toString());
jTextField1_id.setText(jTable1_info.getValueAt(Index, 0).toString());
Image pic=((ImageIcon)jTable1_info.getValueAt(Index, 7)).getImage().getScaledInstance(jLabel1_picframe.getWidth(),jLabel1_picframe.getHeight(),Image.SCALE_SMOOTH);

ImageIcon img=new ImageIcon(pic);

jLabel1_picframe.setIcon(img); 
       
       
   }
    
    
    
    
    private void jButton1_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_editActionPerformed
       
         int id=Integer.valueOf( jTextField1_id.getText());
        String fname=jTextField1_fname.getText();
        String lname=jTextField1_lname.getText();
        String phone=jTextField1_phone.getText();
        String address= jTextArea1_adress.getText();
        String group=jComboBox1_email.getSelectedItem().toString();
        String email=jTextField1_email.getText();
        
        //if the user update data and image
        
                if(imgpath !=null)
                
                {
                    byte[]img=null;  
                    
                    
        try {
            
            Path pth=Paths.get(imgpath);
            
            img=Files.readAllBytes(pth);
          
            
             
       contact c=new contact(id, fname, lname, group ,phone,email,address,img, currentUserId); 
        
        contactQuery cq=new contactQuery();
        cq.UpdateContact(c, true);
         refreshJtable();
        clearFields();
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(mycontactform.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(mycontactform.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                    
                }             
                    
                else{
                    
                    
                   
       contact c=new contact(id, fname, lname, group ,phone,email,address,null, currentUserId); 
        
        contactQuery cq=new contactQuery();
        cq.UpdateContact(c,false);
        
           refreshJtable();
              clearFields();     
                }     
                              
                    
                    
                    
                
        
        
        
        
        
      
        
        
       
    }//GEN-LAST:event_jButton1_editActionPerformed

    public void refreshJtable(){
        
        jTable1_info.setModel(new DefaultTableModel());
         populatedJtable();
         
         
        
        
    }
    
    
    
    
    
    private void jTable1_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_infoMouseClicked
       
        
//get selected row data


int rowIndex=jTable1_info.getSelectedRow();

jTextField1_fname.setText(jTable1_info.getValueAt(rowIndex, 1).toString());


jTextField1_lname.setText(jTable1_info.getValueAt(rowIndex, 2).toString());

jComboBox1_email.setSelectedItem(jTable1_info.getValueAt(rowIndex, 3));
jTextField1_phone.setText(jTable1_info.getValueAt(rowIndex, 4).toString());
jTextField1_email.setText(jTable1_info.getValueAt(rowIndex, 5).toString());
jTextArea1_adress.setText(jTable1_info.getValueAt(rowIndex, 6).toString());
jTextField1_id.setText(jTable1_info.getValueAt(rowIndex, 0).toString());
Image pic=((ImageIcon)jTable1_info.getValueAt(rowIndex, 7)).getImage().getScaledInstance(jLabel1_picframe.getWidth(),jLabel1_picframe.getHeight(),Image.SCALE_SMOOTH);

ImageIcon img=new ImageIcon(pic);

jLabel1_picframe.setIcon(img);

// TODO add your handling code here:
    }//GEN-LAST:event_jTable1_infoMouseClicked

    private void jButton1_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_add1ActionPerformed
//int id=Integer.valueOf( jTextField1_id.getText());
        String fname=jTextField1_fname.getText();
        String lname=jTextField1_lname.getText();
        String phone=jTextField1_phone.getText();
        String address= jTextArea1_adress.getText();
        String group=jComboBox1_email.getSelectedItem().toString();
        String email=jTextField1_email.getText();
        byte[] img=null;
        if(imgpath!=null)
        {
        try {
             
            Path pth=Paths.get(imgpath);
            
            img=Files.readAllBytes(pth);
            
            
                contact c=new contact(null,fname,lname,group,phone,email,address,img,currentUserId);
        
        contactQuery cq= new contactQuery();
        cq.InsertContact(c);
         refreshJtable();
        clearFields();
    }   
        


        
               
            
// TODO add your handling code here:
           catch (FileNotFoundException ex) {
            Logger.getLogger(mycontactform.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(mycontactform.class.getName()).log(Level.SEVERE, null, ex);
        }}

            
        else
        
        {
           JOptionPane.showMessageDialog(null,"Please select Image");        
                
}
        
    }//GEN-LAST:event_jButton1_add1ActionPerformed

    private void jButton1_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_delActionPerformed
        
        int id=Integer.valueOf( jTextField1_id.getText());
        
        contactQuery cq=new contactQuery();
        
        cq.DeleteContact(id);
       refreshJtable();  
        clearFields();
    }//GEN-LAST:event_jButton1_delActionPerformed

    private void jTextField1_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_phoneActionPerformed

    private void jTextField1_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_idActionPerformed

    private void jButton1nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1nextActionPerformed
         
        pos=0;
        showData(pos);
        
        
    }//GEN-LAST:event_jButton1nextActionPerformed

    private void jButton1_rtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_rtActionPerformed
pos--;
showData(pos);

        
        
        
        
        
    }//GEN-LAST:event_jButton1_rtActionPerformed

    private void jButton1_lfnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_lfnextActionPerformed
        
        pos=jTable1_info.getRowCount()-1;
        
        showData(pos);
        
        
    }//GEN-LAST:event_jButton1_lfnextActionPerformed

    private void jButton1_lfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_lfActionPerformed
        
pos++;
showData(pos);



// TODO add your handling code here:
    }//GEN-LAST:event_jButton1_lfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mycontactform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mycontactform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mycontactform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mycontactform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mycontactform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_add1;
    private javax.swing.JButton jButton1_del;
    private javax.swing.JButton jButton1_edit;
    private javax.swing.JButton jButton1_lf;
    private javax.swing.JButton jButton1_lfnext;
    private javax.swing.JButton jButton1_picsel;
    private javax.swing.JButton jButton1_rt;
    private javax.swing.JButton jButton1next;
    private javax.swing.JComboBox<String> jComboBox1_email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_ID;
    private javax.swing.JLabel jLabel1_address;
    private javax.swing.JLabel jLabel1_close;
    private javax.swing.JLabel jLabel1_combo1;
    private javax.swing.JLabel jLabel1_email;
    private javax.swing.JLabel jLabel1_fname;
    private javax.swing.JLabel jLabel1_image;
    private javax.swing.JLabel jLabel1_lname;
    private javax.swing.JLabel jLabel1_mini;
    public javax.swing.JLabel jLabel1_minipic;
    private javax.swing.JLabel jLabel1_mycontact;
    private javax.swing.JLabel jLabel1_phone;
    private javax.swing.JLabel jLabel1_picframe;
    public javax.swing.JLabel jLabel1_usename;
    private javax.swing.JLabel jLabel1_yello;
    private javax.swing.JPanel jPanel1_gray;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator1_fname;
    private javax.swing.JSeparator jSeparator1_fname1;
    private javax.swing.JSeparator jSeparator1_phone;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTable jTable1_info;
    private javax.swing.JTextArea jTextArea1_adress;
    private javax.swing.JTextField jTextField1_email;
    private javax.swing.JTextField jTextField1_fname;
    private javax.swing.JTextField jTextField1_id;
    private javax.swing.JTextField jTextField1_lname;
    private javax.swing.JTextField jTextField1_phone;
    private javax.swing.JPanel mycontact_panel;
    // End of variables declaration//GEN-END:variables

    private Object setIcon(ImageIcon pic) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
