
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shadab
 */
public class signUP_form extends javax.swing.JFrame {

    /**
     * Creates new form signUP_form
     */
    
  String imgpth=null;
    public signUP_form() {
        initComponents();
           this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1_registrasion = new javax.swing.JPanel();
        jLabel1_close = new javax.swing.JLabel();
        jLabel1_minimize = new javax.swing.JLabel();
        jLabel1_register = new javax.swing.JLabel();
        jPanel2_main = new javax.swing.JPanel();
        jLabel1_fname = new javax.swing.JLabel();
        jSeparator1_fname = new javax.swing.JSeparator();
        jTextField1_fname = new javax.swing.JTextField();
        jLabel1_lname = new javax.swing.JLabel();
        jSeparator1_lname = new javax.swing.JSeparator();
        jTextField1_lname = new javax.swing.JTextField();
        jLabel1_uname = new javax.swing.JLabel();
        jSeparator1_username = new javax.swing.JSeparator();
        jTextField1_uname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2_pass = new javax.swing.JLabel();
        jSeparator1_pass = new javax.swing.JSeparator();
        jPasswordField1_pass = new javax.swing.JPasswordField();
        jLabel2_repass = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPasswordField1_repass = new javax.swing.JPasswordField();
        jLabel2_pic = new javax.swing.JLabel();
        jLabel2_picc = new javax.swing.JLabel();
        jButton1_signup = new javax.swing.JButton();
        jButton1_cancel = new javax.swing.JButton();
        jLabel2_login = new javax.swing.JLabel();
        jButton1_browse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1_registrasion.setBackground(new java.awt.Color(0, 181, 204));
        jPanel1_registrasion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1_registrasion.setToolTipText("");

        jLabel1_close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Cancel_32px.png"))); // NOI18N
        jLabel1_close.setText(" ");
        jLabel1_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_closeMouseClicked(evt);
            }
        });

        jLabel1_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Subtract_32px_1.png"))); // NOI18N
        jLabel1_minimize.setText(" ");
        jLabel1_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_minimizeMouseClicked(evt);
            }
        });

        jLabel1_register.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1_register.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel1_register.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_register.setText("Registration Form");

        javax.swing.GroupLayout jPanel1_registrasionLayout = new javax.swing.GroupLayout(jPanel1_registrasion);
        jPanel1_registrasion.setLayout(jPanel1_registrasionLayout);
        jPanel1_registrasionLayout.setHorizontalGroup(
            jPanel1_registrasionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_registrasionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_register)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1_close, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1_registrasionLayout.setVerticalGroup(
            jPanel1_registrasionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_registrasionLayout.createSequentialGroup()
                .addGroup(jPanel1_registrasionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_close, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1_minimize)
                    .addComponent(jLabel1_register))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2_main.setBackground(new java.awt.Color(1, 50, 67));
        jPanel2_main.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2_main.setToolTipText("");

        jLabel1_fname.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1_fname.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1_fname.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_fname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Customer_32px.png"))); // NOI18N
        jLabel1_fname.setText("First Name");

        jTextField1_fname.setBackground(new java.awt.Color(1, 50, 67));
        jTextField1_fname.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField1_fname.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1_fname.setText(" ");
        jTextField1_fname.setBorder(null);

        jLabel1_lname.setBackground(new java.awt.Color(1, 50, 67));
        jLabel1_lname.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1_lname.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_lname.setText("Last Name");

        jTextField1_lname.setBackground(new java.awt.Color(1, 50, 67));
        jTextField1_lname.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jTextField1_lname.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1_lname.setText(" ");
        jTextField1_lname.setBorder(null);

        jLabel1_uname.setBackground(new java.awt.Color(1, 50, 67));
        jLabel1_uname.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1_uname.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_uname.setText("User Name");

        jTextField1_uname.setBackground(new java.awt.Color(1, 50, 67));
        jTextField1_uname.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jTextField1_uname.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1_uname.setText(" ");
        jTextField1_uname.setBorder(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Registration_32px.png"))); // NOI18N
        jLabel1.setText(" ");

        jLabel2_pass.setBackground(new java.awt.Color(1, 50, 67));
        jLabel2_pass.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2_pass.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_pass.setText("password");

        jPasswordField1_pass.setBackground(new java.awt.Color(1, 50, 67));
        jPasswordField1_pass.setFont(new java.awt.Font("Segoe UI Symbol", 0, 10)); // NOI18N
        jPasswordField1_pass.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1_pass.setBorder(null);

        jLabel2_repass.setBackground(new java.awt.Color(1, 50, 67));
        jLabel2_repass.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2_repass.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_repass.setText("Retype pass");

        jPasswordField1_repass.setBackground(new java.awt.Color(1, 50, 67));
        jPasswordField1_repass.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1_repass.setBorder(null);
        jPasswordField1_repass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1_repassActionPerformed(evt);
            }
        });

        jLabel2_pic.setBackground(new java.awt.Color(1, 50, 67));
        jLabel2_pic.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2_pic.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_pic.setText("picture:");

        jLabel2_picc.setBackground(new java.awt.Color(52, 73, 94));
        jLabel2_picc.setText(" ");
        jLabel2_picc.setOpaque(true);

        jButton1_signup.setBackground(new java.awt.Color(0, 230, 64));
        jButton1_signup.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton1_signup.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Member_32px.png"))); // NOI18N
        jButton1_signup.setText("Sign Up");
        jButton1_signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_signupActionPerformed(evt);
            }
        });

        jButton1_cancel.setBackground(new java.awt.Color(219, 10, 91));
        jButton1_cancel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton1_cancel.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Banned_32px.png"))); // NOI18N
        jButton1_cancel.setText("Cancel");
        jButton1_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_cancelMouseClicked(evt);
            }
        });

        jLabel2_login.setBackground(new java.awt.Color(1, 50, 67));
        jLabel2_login.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2_login.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Seesaw_32px.png"))); // NOI18N
        jLabel2_login.setText("Already have account");
        jLabel2_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2_loginMouseClicked(evt);
            }
        });

        jButton1_browse.setBackground(new java.awt.Color(0, 181, 204));
        jButton1_browse.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton1_browse.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_browse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Full_Image_32px.png"))); // NOI18N
        jButton1_browse.setText("Browse");
        jButton1_browse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_browseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2_mainLayout = new javax.swing.GroupLayout(jPanel2_main);
        jPanel2_main.setLayout(jPanel2_mainLayout);
        jPanel2_mainLayout.setHorizontalGroup(
            jPanel2_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_mainLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2_mainLayout.createSequentialGroup()
                        .addComponent(jLabel2_login)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2_mainLayout.createSequentialGroup()
                        .addComponent(jButton1_cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1_signup)
                        .addGap(107, 107, 107))))
            .addGroup(jPanel2_mainLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2_mainLayout.createSequentialGroup()
                            .addGroup(jPanel2_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2_mainLayout.createSequentialGroup()
                                    .addGroup(jPanel2_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1_fname)
                                        .addGroup(jPanel2_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1_uname)
                                            .addComponent(jLabel1_lname)
                                            .addComponent(jLabel2_pass)
                                            .addComponent(jLabel2_repass)))
                                    .addGroup(jPanel2_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2_mainLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField1_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2_mainLayout.createSequentialGroup()
                                            .addGap(5, 5, 5)
                                            .addComponent(jTextField1_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2_mainLayout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addComponent(jPasswordField1_pass))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2_mainLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel2_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField1_uname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jPasswordField1_repass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGap(79, 79, 79))
                        .addGroup(jPanel2_mainLayout.createSequentialGroup()
                            .addGroup(jPanel2_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1_fname, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                .addComponent(jSeparator1_lname)
                                .addComponent(jSeparator1_username))
                            .addGap(58, 58, 58))
                        .addGroup(jPanel2_mainLayout.createSequentialGroup()
                            .addGroup(jPanel2_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(58, 58, 58)))
                    .addGroup(jPanel2_mainLayout.createSequentialGroup()
                        .addComponent(jLabel2_pic)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2_picc, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1_browse)
                        .addGap(52, 52, 52))))
        );
        jPanel2_mainLayout.setVerticalGroup(
            jPanel2_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_mainLayout.createSequentialGroup()
                .addGroup(jPanel2_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2_mainLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1_fname))
                    .addGroup(jPanel2_mainLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jTextField1_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_lname)
                    .addComponent(jTextField1_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_uname)
                    .addComponent(jTextField1_uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1_username, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_pass)
                    .addComponent(jPasswordField1_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2_mainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2_pic)
                        .addGap(206, 206, 206))
                    .addGroup(jPanel2_mainLayout.createSequentialGroup()
                        .addGroup(jPanel2_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2_repass)
                            .addGroup(jPanel2_mainLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jPasswordField1_repass)))
                        .addGroup(jPanel2_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2_mainLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel2_picc, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2_mainLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1_browse)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1_signup)
                            .addComponent(jButton1_cancel))
                        .addGap(32, 32, 32)))
                .addComponent(jLabel2_login)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2_main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1_registrasion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1_registrasion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_closeMouseClicked
       
        
System.exit(0);


// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1_closeMouseClicked

    private void jLabel1_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_minimizeMouseClicked
       
          this.setState(JFrame.ICONIFIED);


// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1_minimizeMouseClicked

    private void jPasswordField1_repassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1_repassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1_repassActionPerformed

    private void jLabel2_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_loginMouseClicked
       
        

   loginform lf= new loginform();
        
      lf.setVisible(true);
        lf.pack();
        lf.setLocationRelativeTo(null);
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();






// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2_loginMouseClicked
//
//    public ImageIcon ResizePic(String picPath)
//    {
//        
//       ImageIcon myimage=new ImageIcon(picPath); 
//        
//      
//    Image img = myimage.getImage().getScaledInstance(jLabel2_picc.getWidth(),  jLabel2_picc.getHeight(),Image.SCALE_SMOOTH);
//       
//       ImageIcon mypicture=new ImageIcon(img);       
//              
//            return mypicture;  
//    }
//    
//    
    
    
    
    
    
    
    
    private void jButton1_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_cancelMouseClicked
        
System.exit(0);





// TODO add your handling code here:
    }//GEN-LAST:event_jButton1_cancelMouseClicked

    private void jButton1_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_browseActionPerformed
       
   myfunc mf=new myfunc();
   
  imgpth= mf.BrowseImage( jLabel2_picc);


 
    }//GEN-LAST:event_jButton1_browseActionPerformed

    public boolean verifdata()
    {
        
       if(jTextField1_fname.getText().equals("")&& jTextField1_lname.getText().equals("")|| jTextField1_uname.getText().equals("")
               || String.valueOf(jPasswordField1_pass.getPassword()).equals("")) 
        
        
       {
          JOptionPane.showMessageDialog(null,"one or more fields are empty");
           return false;
       }
        
           
       
       
       
       else if(!String.valueOf(jPasswordField1_pass.getPassword()).equals(String.valueOf(jPasswordField1_repass.getPassword())))
       {
            JOptionPane.showMessageDialog(null,"incorrect password");
        return false;   
           
    }  
           
    else if(imgpth==null) 
    
    {
      JOptionPane.showMessageDialog(null,"please select the image");   
        return false;
    }
    else{
    return true;
}
    
 
    }  
    
    public boolean ifusernameExit(String un)
    {
        
    boolean uExit=false;    
        
    try {
            PreparedStatement ps;
            ResultSet rs;
            String username= jTextField1_uname.getText();
            
            
            String query="SELECT * FROM `user` WHERE uname= ?";
            
            
            
            
            
            
            ps=myconnection.getconnection().prepareStatement(query);
            
            
            
            ps.setString(1, username);
            
            
            
            rs=ps.executeQuery();
            
            if(rs.next())
            {
                uExit=true;
            }
                
                
    }
        
        catch (SQLException ex) {
            Logger.getLogger(loginform.class.getName()).log(Level.SEVERE, null, ex); 
        
        
            
        
        }
    return uExit;
    }
     
    
    
    
    private void jButton1_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_signupActionPerformed
      
        
         String fname= jTextField1_fname.getText();
            String lname=jTextField1_lname.getText();
            String username=jTextField1_uname.getText();
            String pass= String.valueOf(jPasswordField1_pass.getPassword() );
            
            String r_pass= String.valueOf(jPasswordField1_repass.getPassword() );
            
                 
    
        
        
        if(verifdata())
        
        {
        
        
        
        
         PreparedStatement ps;
        
         String query="INSERT INTO `user`(`fname`, `lname`, `uname`, `pass`, `pic`) VALUES (?,?,?,?,?)";
        
           try {
            ps = myconnection.getconnection().prepareStatement(query);
        
                  ps.setString(1,  fname);
                  ps.setString(2,  lname);
             ps.setString(3,  username);
              
         ps.setString(4,  pass);
             
           
    InputStream img =new FileInputStream(new File(imgpth));
            
         ps.setBlob(5, img);
         
         
         if(ifusernameExit(jTextField1_uname.getText()))
         {
             
             JOptionPane.showMessageDialog(null,"username alreadt exits"); 
         } 
        else
        {
              
          
     
         
            if(ps.executeUpdate()!=0)
                
            {   
                
                JOptionPane.showMessageDialog(null,"account created");    
                
           }
            
           else
            {
             
                JOptionPane.showMessageDialog(null,"something wrong"); 
                
            }
           
         
     }
           }         
        
           
            catch (Exception ex) {
                    Logger.getLogger( signUP_form.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
    }//GEN-LAST:event_jButton1_signupActionPerformed
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signUP_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signUP_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signUP_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signUP_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUP_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_browse;
    private javax.swing.JButton jButton1_cancel;
    private javax.swing.JButton jButton1_signup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_close;
    private javax.swing.JLabel jLabel1_fname;
    private javax.swing.JLabel jLabel1_lname;
    private javax.swing.JLabel jLabel1_minimize;
    private javax.swing.JLabel jLabel1_register;
    private javax.swing.JLabel jLabel1_uname;
    private javax.swing.JLabel jLabel2_login;
    private javax.swing.JLabel jLabel2_pass;
    private javax.swing.JLabel jLabel2_pic;
    private javax.swing.JLabel jLabel2_picc;
    private javax.swing.JLabel jLabel2_repass;
    private javax.swing.JPanel jPanel1_registrasion;
    private javax.swing.JPanel jPanel2_main;
    private javax.swing.JPasswordField jPasswordField1_pass;
    private javax.swing.JPasswordField jPasswordField1_repass;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator1_fname;
    private javax.swing.JSeparator jSeparator1_lname;
    private javax.swing.JSeparator jSeparator1_pass;
    private javax.swing.JSeparator jSeparator1_username;
    private javax.swing.JTextField jTextField1_fname;
    private javax.swing.JTextField jTextField1_lname;
    private javax.swing.JTextField jTextField1_uname;
    // End of variables declaration//GEN-END:variables

    private Icon resizePic(String path) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
